/**
 * Каталог плитки и напольных покрытий — для дизайнеров.
 * Реальные ходовые модели: имитация мрамора, дерева, бетона, метро,
 * марокканская плитка, terrazzo, herringbone, brick.
 *
 * Используется в разделах ПЛАНИРОВЩИК (отделка пола/стен), КАТАЛОГ.
 */

export type TileSurface = "floor" | "wall" | "both";
export type TileMaterial =
  | "porcelain"   // керамогранит
  | "ceramic"     // керамика
  | "marble"      // мрамор натуральный/имитация
  | "stone"       // камень
  | "wood-look"   // дерево-имитация
  | "concrete"    // бетон
  | "mosaic"      // мозаика
  | "brick";      // кирпич декоративный

export type TileStyle =
  | "scandi"
  | "loft"
  | "classic"
  | "minimal"
  | "modern"
  | "japandi"
  | "glamour"
  | "midcentury";

export interface TileItem {
  id: string;
  name: string;
  brand: string;
  collection?: string;
  /** Превью образца — top-view */
  preview: string;
  /** Цвет акцент для UI карточки */
  accent: string;
  /** Размеры одной плитки в см: ширина × высота */
  size: [number, number];
  material: TileMaterial;
  surface: TileSurface;
  style: TileStyle;
  altStyles?: TileStyle[];
  /** Цена за 1 м² в ₽ */
  pricePerM2: number;
  /** Где применяется (комнаты) */
  rooms: ("kitchen" | "bath" | "living" | "bed" | "hall" | "outdoor")[];
  description: string;
  tags: string[];
  popular?: boolean;
}

const TILE_IMG = {
  subwayWhite:   "https://cdn.poehali.dev/projects/ff1052f5-e1cc-4580-9acd-52ad0a25f2e7/files/176da2ca-9517-4357-8523-281b17d0a60d.jpg",
  carraraMarble: "https://cdn.poehali.dev/projects/ff1052f5-e1cc-4580-9acd-52ad0a25f2e7/files/12e9e709-6d82-4fc8-97ad-dfa45ede8f50.jpg",
  concreteGrey:  "https://cdn.poehali.dev/projects/ff1052f5-e1cc-4580-9acd-52ad0a25f2e7/files/65ee7582-289d-4104-b1b4-f62fe15218b5.jpg",
  oakPlank:      "https://cdn.poehali.dev/projects/ff1052f5-e1cc-4580-9acd-52ad0a25f2e7/files/247216d0-42ee-478a-8cbc-9a4b7cbeba3b.jpg",
  moroccan:      "https://cdn.poehali.dev/projects/ff1052f5-e1cc-4580-9acd-52ad0a25f2e7/files/819c86f5-2d0e-4fe1-9e98-741eeb6441e2.jpg",
  hexBlack:      "https://cdn.poehali.dev/projects/ff1052f5-e1cc-4580-9acd-52ad0a25f2e7/files/1511ba69-be90-4b09-b7d6-edeaa8b1ad86.jpg",
  emeraldGloss:  "https://cdn.poehali.dev/projects/ff1052f5-e1cc-4580-9acd-52ad0a25f2e7/files/11f59d0c-97c7-4aa4-8a14-5a4ba941a57f.jpg",
  travertine:    "https://cdn.poehali.dev/projects/ff1052f5-e1cc-4580-9acd-52ad0a25f2e7/files/26228219-014a-412c-ad12-0ef09692774b.jpg",
  terrazzo:      "https://cdn.poehali.dev/projects/ff1052f5-e1cc-4580-9acd-52ad0a25f2e7/files/3e4d7565-6455-4416-94b2-0eb684cb6c1f.jpg",
  calacatta:     "https://cdn.poehali.dev/projects/ff1052f5-e1cc-4580-9acd-52ad0a25f2e7/files/cbba665a-8222-4667-9fbb-9656f495d20a.jpg",
  walnutHerring: "https://cdn.poehali.dev/projects/ff1052f5-e1cc-4580-9acd-52ad0a25f2e7/files/59c62af5-81f1-4651-af3b-be7f36185c69.jpg",
  brickRed:      "https://cdn.poehali.dev/projects/ff1052f5-e1cc-4580-9acd-52ad0a25f2e7/files/b1fd4aa7-fcc2-4d24-a440-5d107ac2520b.jpg",
};

export const TILE_LIBRARY: TileItem[] = [
  {
    id: "tile-subway-white",
    name: "Метро Белая глянец",
    brand: "Kerama Marazzi",
    collection: "Metro",
    preview: TILE_IMG.subwayWhite,
    accent: "#fafafa",
    size: [10, 30],
    material: "ceramic",
    surface: "wall",
    style: "scandi",
    altStyles: ["minimal", "loft", "modern"],
    pricePerM2: 1450,
    rooms: ["kitchen", "bath"],
    description: "Классическая «метро» 10×30 см, белый глянец. Кладётся вразбежку или ёлочкой.",
    tags: ["метро", "subway", "белая", "кухня", "фартук"],
    popular: true,
  },
  {
    id: "tile-carrara",
    name: "Carrara Marble",
    brand: "Italon",
    collection: "Charme",
    preview: TILE_IMG.carraraMarble,
    accent: "#f5f5f4",
    size: [60, 60],
    material: "marble",
    surface: "both",
    style: "classic",
    altStyles: ["glamour", "modern"],
    pricePerM2: 4280,
    rooms: ["bath", "kitchen", "living"],
    description: "Имитация мрамора Каррара 60×60. Полированный керамогранит, серые прожилки.",
    tags: ["мрамор", "carrara", "ванная", "белый"],
    popular: true,
  },
  {
    id: "tile-concrete",
    name: "Concrete Dark",
    brand: "Estima",
    collection: "Loft",
    preview: TILE_IMG.concreteGrey,
    accent: "#52525b",
    size: [60, 60],
    material: "concrete",
    surface: "floor",
    style: "loft",
    altStyles: ["minimal", "modern"],
    pricePerM2: 2150,
    rooms: ["living", "kitchen", "hall", "outdoor"],
    description: "Под бетон 60×60, тёмно-серый. Ректифицированный, минимальный шов.",
    tags: ["бетон", "лофт", "тёмная", "пол"],
  },
  {
    id: "tile-oak-plank",
    name: "Oak Natural Plank",
    brand: "Kerranova",
    collection: "Wood",
    preview: TILE_IMG.oakPlank,
    accent: "#d6c5a8",
    size: [20, 120],
    material: "wood-look",
    surface: "floor",
    style: "scandi",
    altStyles: ["japandi", "modern"],
    pricePerM2: 2680,
    rooms: ["living", "bed", "kitchen", "hall"],
    description: "Под дуб 20×120. Тёплый рельеф, матовая поверхность.",
    tags: ["дерево", "дуб", "доска", "пол"],
    popular: true,
  },
  {
    id: "tile-moroccan",
    name: "Moroccan Pattern",
    brand: "Equipe",
    collection: "Caprice",
    preview: TILE_IMG.moroccan,
    accent: "#1e40af",
    size: [20, 20],
    material: "ceramic",
    surface: "both",
    style: "classic",
    altStyles: ["glamour"],
    pricePerM2: 3850,
    rooms: ["kitchen", "bath", "hall"],
    description: "Марокканский узор 20×20, синий + белый. Смешивается с однотонной.",
    tags: ["узор", "марокко", "синяя"],
  },
  {
    id: "tile-hex-black",
    name: "Hex Black Matt",
    brand: "Equipe",
    collection: "Hexa",
    preview: TILE_IMG.hexBlack,
    accent: "#0a0a0a",
    size: [15, 17],
    material: "porcelain",
    surface: "both",
    style: "minimal",
    altStyles: ["modern", "loft"],
    pricePerM2: 3450,
    rooms: ["bath", "kitchen"],
    description: "Шестигранник 15×17, чёрная матовая. Современный геометричный декор.",
    tags: ["шестигранник", "чёрная", "матовая"],
    popular: true,
  },
  {
    id: "tile-emerald",
    name: "Emerald Gloss",
    brand: "Equipe",
    collection: "Splendours",
    preview: TILE_IMG.emeraldGloss,
    accent: "#047857",
    size: [7, 30],
    material: "ceramic",
    surface: "wall",
    style: "glamour",
    altStyles: ["classic", "modern"],
    pricePerM2: 4150,
    rooms: ["bath", "kitchen"],
    description: "Изумрудно-зелёная глянцевая «соломка» 7×30. Эффект ручной работы.",
    tags: ["зелёная", "глянец", "ванная"],
  },
  {
    id: "tile-travertine",
    name: "Travertino Beige",
    brand: "Italon",
    collection: "Travertine",
    preview: TILE_IMG.travertine,
    accent: "#d6b88c",
    size: [60, 60],
    material: "stone",
    surface: "both",
    style: "classic",
    altStyles: ["modern", "minimal"],
    pricePerM2: 3780,
    rooms: ["bath", "living", "outdoor"],
    description: "Под травертин 60×60, тёплый бежевый. Натуральная фактура.",
    tags: ["травертин", "камень", "бежевая"],
  },
  {
    id: "tile-terrazzo",
    name: "Terrazzo Mix",
    brand: "Marca Corona",
    collection: "Terra",
    preview: TILE_IMG.terrazzo,
    accent: "#e7e5e4",
    size: [60, 60],
    material: "porcelain",
    surface: "floor",
    style: "midcentury",
    altStyles: ["modern", "scandi"],
    pricePerM2: 4250,
    rooms: ["living", "kitchen", "bath", "hall"],
    description: "Терраццо с разноцветной мраморной крошкой на белом фоне.",
    tags: ["terrazzo", "винтаж", "крошка"],
    popular: true,
  },
  {
    id: "tile-calacatta",
    name: "Calacatta Black Gold",
    brand: "Italon",
    collection: "Charme Extra",
    preview: TILE_IMG.calacatta,
    accent: "#171717",
    size: [60, 120],
    material: "marble",
    surface: "both",
    style: "glamour",
    altStyles: ["classic", "modern"],
    pricePerM2: 6850,
    rooms: ["bath", "living", "kitchen"],
    description: "Чёрный мрамор Calacatta с золотыми прожилками 60×120. Премиум.",
    tags: ["мрамор", "чёрный", "золото", "премиум"],
  },
  {
    id: "tile-walnut-herring",
    name: "Walnut Herringbone",
    brand: "Kerranova",
    collection: "Wood Premium",
    preview: TILE_IMG.walnutHerring,
    accent: "#78350f",
    size: [15, 90],
    material: "wood-look",
    surface: "floor",
    style: "classic",
    altStyles: ["midcentury", "modern"],
    pricePerM2: 3650,
    rooms: ["living", "bed", "hall"],
    description: "Под орех «ёлочкой» 15×90. Классический паркет в керамограните.",
    tags: ["дерево", "ёлочка", "herringbone"],
  },
  {
    id: "tile-brick-red",
    name: "Brick Red Loft",
    brand: "Cersanit",
    collection: "Loft",
    preview: TILE_IMG.brickRed,
    accent: "#991b1b",
    size: [6, 25],
    material: "brick",
    surface: "wall",
    style: "loft",
    altStyles: ["midcentury"],
    pricePerM2: 1850,
    rooms: ["living", "kitchen", "hall"],
    description: "Декоративный кирпич 6×25, состаренный красный. Имитация старой кладки.",
    tags: ["кирпич", "лофт", "красный"],
  },

  /* ───────── РАСШИРЕНИЕ: ассортимент по образцу agaudi.ru ───────── */

  // ── МРАМОР И ПРЕМИУМ ───────────────────────────────────────────
  {
    id: "tile-statuario",
    name: "Statuario Venato",
    brand: "Italon",
    collection: "Charme Deluxe",
    preview: TILE_IMG.carraraMarble,
    accent: "#fafaf9",
    size: [80, 80],
    material: "marble",
    surface: "both",
    style: "glamour",
    altStyles: ["classic", "modern"],
    pricePerM2: 5980,
    rooms: ["bath", "living", "kitchen"],
    description: "Имитация мрамора Statuario 80×80. Полированный, тонкие серые прожилки.",
    tags: ["мрамор", "статуарио", "белый", "премиум"],
    popular: true,
  },
  {
    id: "tile-marquinia",
    name: "Marquinia Black",
    brand: "Atlas Concorde",
    collection: "Marvel",
    preview: TILE_IMG.calacatta,
    accent: "#0c0a09",
    size: [60, 60],
    material: "marble",
    surface: "both",
    style: "glamour",
    altStyles: ["modern", "classic"],
    pricePerM2: 5450,
    rooms: ["bath", "living", "hall"],
    description: "Чёрный мрамор Marquinia с белыми прожилками. Лаппато-полировка.",
    tags: ["мрамор", "чёрный", "marquinia"],
  },
  {
    id: "tile-emperador",
    name: "Emperador Brown",
    brand: "Estima",
    collection: "Marble",
    preview: TILE_IMG.travertine,
    accent: "#78350f",
    size: [60, 120],
    material: "marble",
    surface: "both",
    style: "classic",
    altStyles: ["glamour", "midcentury"],
    pricePerM2: 4180,
    rooms: ["bath", "living", "hall"],
    description: "Тёплый коричневый мрамор Emperador. Уютный камень для классики.",
    tags: ["мрамор", "коричневый", "emperador"],
  },
  {
    id: "tile-onyx-honey",
    name: "Onyx Honey",
    brand: "Italon",
    collection: "Stellaris",
    preview: TILE_IMG.travertine,
    accent: "#d97706",
    size: [60, 120],
    material: "marble",
    surface: "wall",
    style: "glamour",
    altStyles: ["classic"],
    pricePerM2: 7280,
    rooms: ["bath", "living"],
    description: "Имитация оникса медового. Подходит для контурной подсветки.",
    tags: ["оникс", "премиум", "глянец"],
  },
  {
    id: "tile-carrara-hex",
    name: "Carrara Hexagon",
    brand: "Equipe",
    collection: "Carrara",
    preview: TILE_IMG.hexBlack,
    accent: "#f5f5f4",
    size: [17, 20],
    material: "marble",
    surface: "wall",
    style: "classic",
    altStyles: ["minimal", "modern"],
    pricePerM2: 3950,
    rooms: ["bath", "kitchen"],
    description: "Шестигранник под мрамор Каррара. Эффектный декор фартука.",
    tags: ["шестигранник", "мрамор", "белый"],
  },

  // ── БЕТОН И ЛОФТ ───────────────────────────────────────────────
  {
    id: "tile-cement-light",
    name: "Cemento Pearl",
    brand: "Marazzi",
    collection: "Plaster",
    preview: TILE_IMG.concreteGrey,
    accent: "#a8a29e",
    size: [60, 120],
    material: "concrete",
    surface: "both",
    style: "minimal",
    altStyles: ["loft", "modern", "japandi"],
    pricePerM2: 2980,
    rooms: ["living", "kitchen", "bath", "hall"],
    description: "Светло-серый бетон 60×120. Большой формат, минимальный шов.",
    tags: ["бетон", "серый", "минимализм"],
    popular: true,
  },
  {
    id: "tile-concrete-anthracite",
    name: "Concrete Anthracite",
    brand: "Atlas Concorde",
    collection: "Boost",
    preview: TILE_IMG.concreteGrey,
    accent: "#27272a",
    size: [80, 80],
    material: "concrete",
    surface: "floor",
    style: "loft",
    altStyles: ["modern", "minimal"],
    pricePerM2: 3450,
    rooms: ["living", "kitchen", "hall", "outdoor"],
    description: "Тёмный антрацит-бетон. Антискользящая фактура R10.",
    tags: ["бетон", "тёмный", "антискольжение"],
  },
  {
    id: "tile-cement-warm",
    name: "Cemento Sand",
    brand: "Estima",
    collection: "Loft",
    preview: TILE_IMG.travertine,
    accent: "#d6b88c",
    size: [60, 60],
    material: "concrete",
    surface: "both",
    style: "japandi",
    altStyles: ["minimal", "scandi"],
    pricePerM2: 2380,
    rooms: ["living", "bath", "hall"],
    description: "Тёплый песочный бетон. Уютная альтернатива холодному серому.",
    tags: ["бетон", "бежевый", "тёплый"],
  },
  {
    id: "tile-microcement-white",
    name: "Microcement White",
    brand: "Porcelanosa",
    collection: "Bottega",
    preview: TILE_IMG.subwayWhite,
    accent: "#fafaf9",
    size: [120, 120],
    material: "concrete",
    surface: "both",
    style: "minimal",
    altStyles: ["modern", "japandi"],
    pricePerM2: 5680,
    rooms: ["living", "bath", "kitchen"],
    description: "Микроцемент белый, формат 120×120. Бесшовная отделка стен и пола.",
    tags: ["микроцемент", "белый", "большой формат"],
  },

  // ── ПОД ДЕРЕВО ─────────────────────────────────────────────────
  {
    id: "tile-larch",
    name: "Larch Smoked",
    brand: "Italon",
    collection: "Element Wood",
    preview: TILE_IMG.oakPlank,
    accent: "#8b6f47",
    size: [22, 90],
    material: "wood-look",
    surface: "floor",
    style: "modern",
    altStyles: ["loft", "midcentury"],
    pricePerM2: 2450,
    rooms: ["living", "bed", "kitchen"],
    description: "Лиственница копчёная 22×90. Глубокий рисунок годовых колец.",
    tags: ["дерево", "лиственница", "копчёная"],
  },
  {
    id: "tile-ash-white",
    name: "Ash Whitewash",
    brand: "Kerranova",
    collection: "Wood Whitewashed",
    preview: TILE_IMG.oakPlank,
    accent: "#e7e5e4",
    size: [20, 120],
    material: "wood-look",
    surface: "floor",
    style: "scandi",
    altStyles: ["japandi", "minimal"],
    pricePerM2: 2780,
    rooms: ["living", "bed", "hall"],
    description: "Беленый ясень. Светлый сканди-пол с лёгкой текстурой.",
    tags: ["дерево", "беленый", "ясень", "светлый"],
    popular: true,
  },
  {
    id: "tile-teak-natural",
    name: "Teak Natural",
    brand: "Marca Corona",
    collection: "TraVerSo",
    preview: TILE_IMG.oakPlank,
    accent: "#a16207",
    size: [20, 120],
    material: "wood-look",
    surface: "both",
    style: "midcentury",
    altStyles: ["modern", "classic"],
    pricePerM2: 3280,
    rooms: ["living", "kitchen", "outdoor"],
    description: "Тиковое дерево с тёплым медовым оттенком. Морозоустойчивый.",
    tags: ["дерево", "тик", "тёплый"],
  },
  {
    id: "tile-oak-herring-narrow",
    name: "Oak Herringbone Narrow",
    brand: "Italon",
    collection: "NL-Wood",
    preview: TILE_IMG.walnutHerring,
    accent: "#a8a29e",
    size: [10, 70],
    material: "wood-look",
    surface: "floor",
    style: "scandi",
    altStyles: ["classic", "japandi"],
    pricePerM2: 3150,
    rooms: ["living", "bed", "hall"],
    description: "Узкая ёлочка под дуб 10×70. Французский паркетный рисунок.",
    tags: ["ёлочка", "паркет", "дуб"],
  },
  {
    id: "tile-walnut-dark",
    name: "Walnut Dark Plank",
    brand: "Estima",
    collection: "Brigantina",
    preview: TILE_IMG.oakPlank,
    accent: "#451a03",
    size: [20, 120],
    material: "wood-look",
    surface: "floor",
    style: "classic",
    altStyles: ["midcentury", "glamour"],
    pricePerM2: 2980,
    rooms: ["living", "bed", "hall"],
    description: "Тёмный орех 20×120. Богатый венге-оттенок для классики.",
    tags: ["дерево", "орех", "тёмный"],
  },

  // ── МЕТРО, КАБАНЧИК ────────────────────────────────────────────
  {
    id: "tile-subway-mint",
    name: "Метро Мятная",
    brand: "Equipe",
    collection: "Evolution",
    preview: TILE_IMG.subwayWhite,
    accent: "#a7f3d0",
    size: [7, 30],
    material: "ceramic",
    surface: "wall",
    style: "scandi",
    altStyles: ["minimal", "modern"],
    pricePerM2: 1890,
    rooms: ["kitchen", "bath"],
    description: "Кабанчик пастельно-мятный 7,5×30. Свежий сканди-фартук.",
    tags: ["метро", "мятная", "пастельная"],
  },
  {
    id: "tile-subway-black",
    name: "Метро Чёрная Матт",
    brand: "Cersanit",
    collection: "Metro",
    preview: TILE_IMG.subwayWhite,
    accent: "#0a0a0a",
    size: [10, 30],
    material: "ceramic",
    surface: "wall",
    style: "loft",
    altStyles: ["modern", "midcentury"],
    pricePerM2: 1480,
    rooms: ["kitchen", "bath"],
    description: "Метро 10×30 чёрная матовая. Контрастный фартук в стиле loft.",
    tags: ["метро", "чёрная", "матовая"],
    popular: true,
  },
  {
    id: "tile-subway-pink",
    name: "Метро Пыльная Роза",
    brand: "Equipe",
    collection: "Country",
    preview: TILE_IMG.emeraldGloss,
    accent: "#fbcfe8",
    size: [7, 20],
    material: "ceramic",
    surface: "wall",
    style: "glamour",
    altStyles: ["classic", "scandi"],
    pricePerM2: 2280,
    rooms: ["bath", "kitchen"],
    description: "Кабанчик пыльно-розовый 7×20. Эффект ручной работы, лёгкий блеск.",
    tags: ["метро", "розовая", "глянец"],
  },
  {
    id: "tile-subway-mustard",
    name: "Метро Горчичная",
    brand: "Equipe",
    collection: "Splendours",
    preview: TILE_IMG.emeraldGloss,
    accent: "#ca8a04",
    size: [7, 30],
    material: "ceramic",
    surface: "wall",
    style: "midcentury",
    altStyles: ["loft", "classic"],
    pricePerM2: 4280,
    rooms: ["kitchen", "bath"],
    description: "Горчичный кабанчик с лёгким блеском. Тёплый ретро-акцент.",
    tags: ["метро", "горчичная", "ретро"],
  },

  // ── ТЕРРАЦЦО, ПРИНТЫ И ОРНАМЕНТ ────────────────────────────────
  {
    id: "tile-terrazzo-mini",
    name: "Terrazzo Mini Black",
    brand: "Marca Corona",
    collection: "Terra",
    preview: TILE_IMG.terrazzo,
    accent: "#1c1917",
    size: [60, 60],
    material: "porcelain",
    surface: "floor",
    style: "modern",
    altStyles: ["midcentury", "loft"],
    pricePerM2: 4480,
    rooms: ["living", "kitchen", "bath", "hall"],
    description: "Терраццо тёмный с мелкой крошкой. Графичный пол.",
    tags: ["terrazzo", "чёрный", "винтаж"],
  },
  {
    id: "tile-terrazzo-pastel",
    name: "Terrazzo Pastel",
    brand: "Peronda",
    collection: "Mews",
    preview: TILE_IMG.terrazzo,
    accent: "#fef3c7",
    size: [25, 25],
    material: "porcelain",
    surface: "both",
    style: "scandi",
    altStyles: ["midcentury"],
    pricePerM2: 3780,
    rooms: ["bath", "kitchen", "living"],
    description: "Терраццо с пастельной крошкой. Отлично смотрится на стенах ванной.",
    tags: ["terrazzo", "пастельная", "крошка"],
  },
  {
    id: "tile-azulejo-blue",
    name: "Azulejo Blue Pattern",
    brand: "Vives",
    collection: "1900",
    preview: TILE_IMG.moroccan,
    accent: "#1d4ed8",
    size: [20, 20],
    material: "ceramic",
    surface: "both",
    style: "classic",
    altStyles: ["glamour", "midcentury"],
    pricePerM2: 4180,
    rooms: ["kitchen", "bath", "hall"],
    description: "Португальский азулежу 20×20. Сине-белый узор.",
    tags: ["узор", "азулежу", "португалия"],
  },
  {
    id: "tile-cement-victorian",
    name: "Victorian Encaustic",
    brand: "Equipe",
    collection: "Caprice",
    preview: TILE_IMG.moroccan,
    accent: "#475569",
    size: [20, 20],
    material: "ceramic",
    surface: "floor",
    style: "classic",
    altStyles: ["midcentury", "glamour"],
    pricePerM2: 3950,
    rooms: ["hall", "bath", "kitchen"],
    description: "Викторианский цементный узор 20×20. Микс из 6 декоров.",
    tags: ["узор", "цементная", "викторианский"],
  },

  // ── ШЕСТИГРАННИКИ И ГЕОМЕТРИЯ ──────────────────────────────────
  {
    id: "tile-hex-white",
    name: "Hex White Matt",
    brand: "Equipe",
    collection: "Hexa",
    preview: TILE_IMG.hexBlack,
    accent: "#fafafa",
    size: [15, 17],
    material: "porcelain",
    surface: "both",
    style: "scandi",
    altStyles: ["minimal", "modern"],
    pricePerM2: 3250,
    rooms: ["bath", "kitchen"],
    description: "Шестигранник 15×17 белый матовый. Свежий минимализм.",
    tags: ["шестигранник", "белая", "матовая"],
  },
  {
    id: "tile-hex-emerald",
    name: "Hex Emerald",
    brand: "Equipe",
    collection: "Magical",
    preview: TILE_IMG.emeraldGloss,
    accent: "#047857",
    size: [15, 17],
    material: "ceramic",
    surface: "wall",
    style: "glamour",
    altStyles: ["classic", "midcentury"],
    pricePerM2: 4380,
    rooms: ["bath", "kitchen"],
    description: "Изумрудный шестигранник с глянцем. Smaragd-эффект.",
    tags: ["шестигранник", "зелёная", "глянец"],
  },
  {
    id: "tile-fish-scale",
    name: "Fish Scale Pearl",
    brand: "Vives",
    collection: "Cottage",
    preview: TILE_IMG.subwayWhite,
    accent: "#e0f2fe",
    size: [12, 12],
    material: "ceramic",
    surface: "wall",
    style: "glamour",
    altStyles: ["classic", "scandi"],
    pricePerM2: 4980,
    rooms: ["bath", "kitchen"],
    description: "Декоративная «рыбья чешуя» жемчужно-голубая. Эффект перламутра.",
    tags: ["чешуя", "scallop", "перламутр"],
  },

  // ── КАМЕНЬ И УЛИЧНАЯ ───────────────────────────────────────────
  {
    id: "tile-stone-grey",
    name: "Stone Pietra Grigia",
    brand: "Atlas Concorde",
    collection: "Klif",
    preview: TILE_IMG.concreteGrey,
    accent: "#57534e",
    size: [60, 120],
    material: "stone",
    surface: "floor",
    style: "modern",
    altStyles: ["loft", "minimal"],
    pricePerM2: 3680,
    rooms: ["living", "kitchen", "outdoor"],
    description: "Имитация серого сланца, формат 60×120. Антискольжение R11.",
    tags: ["камень", "сланец", "улица"],
  },
  {
    id: "tile-stone-quartzite",
    name: "Quartzite White",
    brand: "Italon",
    collection: "Genesis",
    preview: TILE_IMG.travertine,
    accent: "#f5f5f4",
    size: [60, 60],
    material: "stone",
    surface: "both",
    style: "minimal",
    altStyles: ["modern", "scandi"],
    pricePerM2: 4080,
    rooms: ["bath", "living", "kitchen"],
    description: "Под кварцит белый, тонкие графитовые жилки. Spa-эстетика.",
    tags: ["кварцит", "камень", "белый"],
  },
  {
    id: "tile-basalt",
    name: "Basalt Black",
    brand: "Estima",
    collection: "Hard",
    preview: TILE_IMG.concreteGrey,
    accent: "#0c0a09",
    size: [30, 60],
    material: "stone",
    surface: "floor",
    style: "loft",
    altStyles: ["modern"],
    pricePerM2: 2280,
    rooms: ["hall", "kitchen", "outdoor"],
    description: "Базальт чёрный, шероховатый. Морозостойкий, для крыльца.",
    tags: ["базальт", "улица", "морозостойкий"],
  },

  // ── КИРПИЧ И BRICK ─────────────────────────────────────────────
  {
    id: "tile-brick-white",
    name: "Brick White Old",
    brand: "Cersanit",
    collection: "Loft",
    preview: TILE_IMG.subwayWhite,
    accent: "#f5f5f4",
    size: [6, 25],
    material: "brick",
    surface: "wall",
    style: "loft",
    altStyles: ["scandi", "modern"],
    pricePerM2: 1750,
    rooms: ["living", "kitchen", "hall", "bed"],
    description: "Состаренный белый кирпич 6×25. Светлый loft, расширяет пространство.",
    tags: ["кирпич", "белый", "состаренный"],
    popular: true,
  },
  {
    id: "tile-brick-grey",
    name: "Brick Grey Stone",
    brand: "Cersanit",
    collection: "Loft",
    preview: TILE_IMG.concreteGrey,
    accent: "#57534e",
    size: [6, 25],
    material: "brick",
    surface: "wall",
    style: "loft",
    altStyles: ["modern", "midcentury"],
    pricePerM2: 1980,
    rooms: ["living", "kitchen", "hall"],
    description: "Серый кирпич 6×25 с лёгкой шероховатостью. Универсальный loft.",
    tags: ["кирпич", "серый", "лофт"],
  },

  // ── МОЗАИКА ────────────────────────────────────────────────────
  {
    id: "tile-mosaic-marble",
    name: "Mosaic Carrara Mix",
    brand: "Italon",
    collection: "Charme Mosaico",
    preview: TILE_IMG.carraraMarble,
    accent: "#f5f5f4",
    size: [30, 30],
    material: "mosaic",
    surface: "wall",
    style: "classic",
    altStyles: ["glamour", "modern"],
    pricePerM2: 5680,
    rooms: ["bath", "kitchen"],
    description: "Мозаика-микс из мрамора Каррара. Декор для ниш и фартука.",
    tags: ["мозаика", "мрамор", "декор"],
  },
  {
    id: "tile-mosaic-pebble",
    name: "Pebble Beach",
    brand: "Equipe",
    collection: "Stone",
    preview: TILE_IMG.travertine,
    accent: "#d6c5a8",
    size: [30, 30],
    material: "mosaic",
    surface: "floor",
    style: "japandi",
    altStyles: ["scandi", "minimal"],
    pricePerM2: 5280,
    rooms: ["bath", "outdoor"],
    description: "Галька морская натуральная. Spa-зона, душевые поддоны.",
    tags: ["мозаика", "галька", "spa"],
  },
  {
    id: "tile-mosaic-glass-blue",
    name: "Mosaic Glass Aqua",
    brand: "Vidrepur",
    collection: "Pool",
    preview: TILE_IMG.emeraldGloss,
    accent: "#0ea5e9",
    size: [30, 30],
    material: "mosaic",
    surface: "wall",
    style: "modern",
    altStyles: ["glamour"],
    pricePerM2: 4380,
    rooms: ["bath", "outdoor"],
    description: "Стеклянная мозаика аква-голубая. Подходит для бассейна.",
    tags: ["мозаика", "стекло", "бассейн"],
  },

  // ── БОЛЬШОЙ ФОРМАТ И ТРЕНДЫ ────────────────────────────────────
  {
    id: "tile-slab-calacatta",
    name: "Slab Calacatta XL",
    brand: "Atlas Concorde",
    collection: "Marvel Edge",
    preview: TILE_IMG.carraraMarble,
    accent: "#fafaf9",
    size: [120, 240],
    material: "marble",
    surface: "both",
    style: "glamour",
    altStyles: ["modern", "classic"],
    pricePerM2: 9850,
    rooms: ["bath", "living", "kitchen"],
    description: "Слэб 120×240 под Calacatta. Бесшовные стены и столешницы.",
    tags: ["слэб", "большой формат", "премиум"],
    popular: true,
  },
  {
    id: "tile-slab-concrete",
    name: "Slab Concrete XL",
    brand: "Marazzi",
    collection: "Grande",
    preview: TILE_IMG.concreteGrey,
    accent: "#71717a",
    size: [120, 240],
    material: "concrete",
    surface: "both",
    style: "minimal",
    altStyles: ["modern", "loft"],
    pricePerM2: 7480,
    rooms: ["living", "kitchen", "bath"],
    description: "Бетон-слэб 120×240. Минимум швов, максимум монолитности.",
    tags: ["слэб", "бетон", "большой формат"],
  },
  {
    id: "tile-pearl-3d",
    name: "Pearl 3D Wave",
    brand: "Porcelanosa",
    collection: "Prada",
    preview: TILE_IMG.subwayWhite,
    accent: "#fafaf9",
    size: [33, 100],
    material: "ceramic",
    surface: "wall",
    style: "modern",
    altStyles: ["minimal", "glamour"],
    pricePerM2: 5980,
    rooms: ["living", "bath", "bed"],
    description: "Объёмная 3D-плитка с волной 33×100. Игра света на стене.",
    tags: ["3D", "рельеф", "акцентная стена"],
  },

  // ── ЦВЕТНЫЕ И ХАРАКТЕРНЫЕ ──────────────────────────────────────
  {
    id: "tile-navy-gloss",
    name: "Navy Blue Gloss",
    brand: "Equipe",
    collection: "Splendours",
    preview: TILE_IMG.emeraldGloss,
    accent: "#1e3a8a",
    size: [10, 30],
    material: "ceramic",
    surface: "wall",
    style: "glamour",
    altStyles: ["classic", "midcentury"],
    pricePerM2: 4180,
    rooms: ["bath", "kitchen"],
    description: "Тёмно-синий глянец 10×30. Глубокий navy-эффект.",
    tags: ["синяя", "navy", "глянец"],
  },
  {
    id: "tile-terracotta",
    name: "Terracotta Cotto",
    brand: "Marca Corona",
    collection: "Terraviva",
    preview: TILE_IMG.brickRed,
    accent: "#c2410c",
    size: [20, 20],
    material: "ceramic",
    surface: "floor",
    style: "midcentury",
    altStyles: ["classic", "loft"],
    pricePerM2: 2950,
    rooms: ["kitchen", "hall", "outdoor"],
    description: "Терракотовый котто 20×20. Тёплый итальянский деревенский стиль.",
    tags: ["терракота", "котто", "тёплая"],
  },
  {
    id: "tile-sage-matte",
    name: "Sage Green Matte",
    brand: "Peronda",
    collection: "Harmony",
    preview: TILE_IMG.emeraldGloss,
    accent: "#65a30d",
    size: [11, 25],
    material: "ceramic",
    surface: "wall",
    style: "japandi",
    altStyles: ["scandi", "modern"],
    pricePerM2: 3580,
    rooms: ["bath", "kitchen", "living"],
    description: "Шалфейно-зелёный 11×25 матовый. Тренд japandi 2024.",
    tags: ["зелёная", "шалфей", "матовая"],
    popular: true,
  },

  /* ───────── РАСШИРЕНИЕ #2: +35 позиций (полный ассортимент агауди-стайл) ───────── */

  // ── МРАМОР: ещё коллекции ──────────────────────────────────────
  {
    id: "tile-volakas",
    name: "Volakas Greek",
    brand: "Italon",
    collection: "Magnetique",
    preview: TILE_IMG.carraraMarble,
    accent: "#f5f5f4",
    size: [60, 120],
    material: "marble",
    surface: "both",
    style: "classic",
    altStyles: ["glamour", "modern"],
    pricePerM2: 5380,
    rooms: ["bath", "living", "kitchen"],
    description: "Греческий мрамор Volakas с серо-золотыми прожилками 60×120.",
    tags: ["мрамор", "греческий", "белый"],
  },
  {
    id: "tile-portoro",
    name: "Portoro Gold Black",
    brand: "Atlas Concorde",
    collection: "Marvel Edge",
    preview: TILE_IMG.calacatta,
    accent: "#0c0a09",
    size: [60, 120],
    material: "marble",
    surface: "wall",
    style: "glamour",
    altStyles: ["classic"],
    pricePerM2: 7980,
    rooms: ["bath", "living"],
    description: "Чёрный мрамор Portoro с яркими золотыми жилами. Премиум-сегмент.",
    tags: ["мрамор", "portoro", "чёрный", "золото"],
    popular: true,
  },
  {
    id: "tile-marble-mix",
    name: "Calacatta Mix Slim",
    brand: "Estima",
    collection: "Bernini",
    preview: TILE_IMG.carraraMarble,
    accent: "#fafaf9",
    size: [30, 60],
    material: "marble",
    surface: "both",
    style: "modern",
    altStyles: ["minimal", "scandi"],
    pricePerM2: 2680,
    rooms: ["bath", "kitchen", "hall"],
    description: "Мраморный микс 30×60. Бюджетная альтернатива большим форматам.",
    tags: ["мрамор", "белый", "бюджет"],
  },
  {
    id: "tile-marble-pinkish",
    name: "Rosa Aurora",
    brand: "Italon",
    collection: "Charme Pearl",
    preview: TILE_IMG.travertine,
    accent: "#fda4af",
    size: [60, 60],
    material: "marble",
    surface: "wall",
    style: "glamour",
    altStyles: ["classic"],
    pricePerM2: 5180,
    rooms: ["bath", "living", "bed"],
    description: "Розовый мрамор Aurora с лёгкими бежевыми прожилками. Романтичный.",
    tags: ["мрамор", "розовый", "пастель"],
  },

  // ── ДЕРЕВО: ещё породы ─────────────────────────────────────────
  {
    id: "tile-pine-natural",
    name: "Pine Scandi",
    brand: "Peronda",
    collection: "Foresta",
    preview: TILE_IMG.oakPlank,
    accent: "#fcd34d",
    size: [20, 90],
    material: "wood-look",
    surface: "floor",
    style: "scandi",
    altStyles: ["japandi", "modern"],
    pricePerM2: 2280,
    rooms: ["living", "bed", "kitchen"],
    description: "Сосна с тёплым желтоватым оттенком 20×90. Сканди-уют.",
    tags: ["дерево", "сосна", "сканди"],
  },
  {
    id: "tile-cherry-vintage",
    name: "Cherry Vintage",
    brand: "Marca Corona",
    collection: "TraVerSo",
    preview: TILE_IMG.brickRed,
    accent: "#9f1239",
    size: [20, 120],
    material: "wood-look",
    surface: "floor",
    style: "midcentury",
    altStyles: ["classic", "loft"],
    pricePerM2: 3380,
    rooms: ["living", "bed"],
    description: "Винтажная вишня с глубоким красно-коричневым тоном 20×120.",
    tags: ["дерево", "вишня", "винтаж"],
  },
  {
    id: "tile-bamboo",
    name: "Bamboo Light",
    brand: "Vives",
    collection: "Bamboo",
    preview: TILE_IMG.oakPlank,
    accent: "#fef3c7",
    size: [15, 90],
    material: "wood-look",
    surface: "floor",
    style: "japandi",
    altStyles: ["scandi", "modern"],
    pricePerM2: 2780,
    rooms: ["living", "bed", "kitchen"],
    description: "Бамбук светлый, тонкий рисунок волокон. Японская эстетика.",
    tags: ["дерево", "бамбук", "japandi"],
  },
  {
    id: "tile-driftwood",
    name: "Driftwood Grey",
    brand: "Estima",
    collection: "Brigantina",
    preview: TILE_IMG.concreteGrey,
    accent: "#a8a29e",
    size: [22, 90],
    material: "wood-look",
    surface: "both",
    style: "modern",
    altStyles: ["loft", "minimal"],
    pricePerM2: 2480,
    rooms: ["living", "bath", "outdoor"],
    description: "Серый driftwood с лёгкой потёртостью. Подходит для ванной.",
    tags: ["дерево", "серое", "driftwood"],
  },

  // ── БЕТОН: цвета и форматы ─────────────────────────────────────
  {
    id: "tile-cement-graphite",
    name: "Cement Graphite",
    brand: "Cersanit",
    collection: "Concrete",
    preview: TILE_IMG.concreteGrey,
    accent: "#1f2937",
    size: [60, 60],
    material: "concrete",
    surface: "floor",
    style: "loft",
    altStyles: ["modern", "minimal"],
    pricePerM2: 1680,
    rooms: ["living", "kitchen", "hall"],
    description: "Графитовый бетон 60×60, бюджетный лофт-вариант.",
    tags: ["бетон", "графит", "бюджет"],
  },
  {
    id: "tile-cement-rust",
    name: "Concrete Rust Patina",
    brand: "Marazzi",
    collection: "Mineral",
    preview: TILE_IMG.brickRed,
    accent: "#9a3412",
    size: [60, 60],
    material: "concrete",
    surface: "floor",
    style: "loft",
    altStyles: ["midcentury"],
    pricePerM2: 2980,
    rooms: ["living", "kitchen", "hall"],
    description: "Бетон с эффектом ржавчины. Промышленная эстетика.",
    tags: ["бетон", "ржавчина", "патина"],
  },
  {
    id: "tile-microcement-graphite",
    name: "Microcement Graphite",
    brand: "Porcelanosa",
    collection: "Bottega",
    preview: TILE_IMG.concreteGrey,
    accent: "#27272a",
    size: [120, 120],
    material: "concrete",
    surface: "both",
    style: "minimal",
    altStyles: ["modern", "loft"],
    pricePerM2: 5980,
    rooms: ["living", "bath", "kitchen"],
    description: "Микроцемент тёмный графит, формат 120×120. Монолитные стены.",
    tags: ["микроцемент", "графит", "большой формат"],
    popular: true,
  },

  // ── МЕТРО: ещё цвета ───────────────────────────────────────────
  {
    id: "tile-subway-cream",
    name: "Метро Кремовая",
    brand: "Cersanit",
    collection: "Evolution",
    preview: TILE_IMG.subwayWhite,
    accent: "#fef3c7",
    size: [10, 30],
    material: "ceramic",
    surface: "wall",
    style: "scandi",
    altStyles: ["classic", "japandi"],
    pricePerM2: 1380,
    rooms: ["kitchen", "bath"],
    description: "Кремовая метро 10×30 матовая. Тёплая нейтральная база.",
    tags: ["метро", "кремовая", "матовая"],
  },
  {
    id: "tile-subway-grey",
    name: "Метро Графит",
    brand: "Equipe",
    collection: "Country",
    preview: TILE_IMG.concreteGrey,
    accent: "#52525b",
    size: [7, 20],
    material: "ceramic",
    surface: "wall",
    style: "loft",
    altStyles: ["modern", "midcentury"],
    pricePerM2: 1980,
    rooms: ["kitchen", "bath"],
    description: "Графитовый кабанчик с эффектом ручной работы 7×20.",
    tags: ["метро", "графит", "ручная работа"],
  },
  {
    id: "tile-subway-burgundy",
    name: "Метро Бордо",
    brand: "Equipe",
    collection: "Splendours",
    preview: TILE_IMG.brickRed,
    accent: "#7c2d12",
    size: [7, 30],
    material: "ceramic",
    surface: "wall",
    style: "glamour",
    altStyles: ["classic", "midcentury"],
    pricePerM2: 4380,
    rooms: ["bath", "kitchen", "living"],
    description: "Бордовый кабанчик с лёгким блеском. Дорогой ретро-акцент.",
    tags: ["метро", "бордо", "глянец"],
  },
  {
    id: "tile-subway-mint-glossy",
    name: "Метро Шалфей Глянец",
    brand: "Vives",
    collection: "Aranda",
    preview: TILE_IMG.emeraldGloss,
    accent: "#86efac",
    size: [10, 30],
    material: "ceramic",
    surface: "wall",
    style: "japandi",
    altStyles: ["scandi"],
    pricePerM2: 2580,
    rooms: ["kitchen", "bath"],
    description: "Метро шалфейная глянцевая. Свежий fresh-кухонный вариант.",
    tags: ["метро", "зелёная", "шалфей"],
  },

  // ── ОРНАМЕНТ И ЭТНИКА ─────────────────────────────────────────
  {
    id: "tile-chevron-marble",
    name: "Chevron Carrara",
    brand: "Italon",
    collection: "Charme",
    preview: TILE_IMG.walnutHerring,
    accent: "#fafaf9",
    size: [9, 36],
    material: "marble",
    surface: "wall",
    style: "classic",
    altStyles: ["glamour", "modern"],
    pricePerM2: 5680,
    rooms: ["bath", "living", "kitchen"],
    description: "Шеврон под мрамор Каррара. Французская элегантность.",
    tags: ["шеврон", "мрамор", "паркет"],
  },
  {
    id: "tile-mediterranean",
    name: "Mediterranean Mix",
    brand: "Equipe",
    collection: "Art Nouveau",
    preview: TILE_IMG.moroccan,
    accent: "#0369a1",
    size: [20, 20],
    material: "ceramic",
    surface: "both",
    style: "midcentury",
    altStyles: ["classic", "glamour"],
    pricePerM2: 4580,
    rooms: ["kitchen", "bath", "hall"],
    description: "Средиземноморская смесь узоров 20×20. Каждая плитка уникальна.",
    tags: ["узор", "средиземноморский", "микс"],
  },
  {
    id: "tile-art-deco",
    name: "Art Deco Gold",
    brand: "Peronda",
    collection: "1900",
    preview: TILE_IMG.moroccan,
    accent: "#a16207",
    size: [25, 25],
    material: "ceramic",
    surface: "wall",
    style: "glamour",
    altStyles: ["classic", "midcentury"],
    pricePerM2: 5280,
    rooms: ["bath", "kitchen", "living"],
    description: "Ар-деко с золотыми вставками 25×25. Глянцевая, премиум.",
    tags: ["ар-деко", "золото", "премиум"],
  },
  {
    id: "tile-japanese-wave",
    name: "Seigaiha Indigo",
    brand: "Vives",
    collection: "Japon",
    preview: TILE_IMG.moroccan,
    accent: "#1e40af",
    size: [20, 20],
    material: "ceramic",
    surface: "wall",
    style: "japandi",
    altStyles: ["modern", "minimal"],
    pricePerM2: 4180,
    rooms: ["bath", "kitchen"],
    description: "Японский орнамент сейгаиха «волна» индиго. Эстетика wabi-sabi.",
    tags: ["узор", "japandi", "волна"],
  },

  // ── ШЕСТИГРАННИК: ещё цвета ────────────────────────────────────
  {
    id: "tile-hex-marble",
    name: "Hex Calacatta",
    brand: "Italon",
    collection: "Charme",
    preview: TILE_IMG.hexBlack,
    accent: "#fafaf9",
    size: [17, 20],
    material: "marble",
    surface: "wall",
    style: "glamour",
    altStyles: ["classic", "modern"],
    pricePerM2: 5180,
    rooms: ["bath", "kitchen"],
    description: "Шестигранник под мрамор Calacatta. Премиум-фартук.",
    tags: ["шестигранник", "мрамор", "белый"],
  },
  {
    id: "tile-hex-blush",
    name: "Hex Blush Pink",
    brand: "Equipe",
    collection: "Magical",
    preview: TILE_IMG.emeraldGloss,
    accent: "#fbcfe8",
    size: [15, 17],
    material: "ceramic",
    surface: "wall",
    style: "scandi",
    altStyles: ["glamour"],
    pricePerM2: 3580,
    rooms: ["bath", "kitchen"],
    description: "Шестигранник пыльно-розовый матовый. Нежный сканди-акцент.",
    tags: ["шестигранник", "розовый", "пастель"],
  },
  {
    id: "tile-diamond",
    name: "Diamond Mosaic",
    brand: "Vidrepur",
    collection: "Geometry",
    preview: TILE_IMG.subwayWhite,
    accent: "#e5e7eb",
    size: [15, 25],
    material: "ceramic",
    surface: "wall",
    style: "modern",
    altStyles: ["minimal", "glamour"],
    pricePerM2: 4980,
    rooms: ["bath", "kitchen"],
    description: "Геометрия «алмаз» — ромбы, образующие 3D-эффект.",
    tags: ["ромб", "алмаз", "3D"],
  },

  // ── КАМЕНЬ И ТРАВЕРТИН ─────────────────────────────────────────
  {
    id: "tile-travertine-cross",
    name: "Travertino Crosscut",
    brand: "Marazzi",
    collection: "Mystone",
    preview: TILE_IMG.travertine,
    accent: "#fbbf24",
    size: [60, 120],
    material: "stone",
    surface: "both",
    style: "classic",
    altStyles: ["modern", "minimal"],
    pricePerM2: 4280,
    rooms: ["bath", "living", "kitchen"],
    description: "Травертин с поперечным распилом. Натуральный рисунок дыр и пустот.",
    tags: ["травертин", "крупный формат", "spa"],
  },
  {
    id: "tile-limestone",
    name: "Limestone Bone",
    brand: "Atlas Concorde",
    collection: "Klif",
    preview: TILE_IMG.travertine,
    accent: "#e7e5e4",
    size: [80, 80],
    material: "stone",
    surface: "both",
    style: "minimal",
    altStyles: ["modern", "japandi"],
    pricePerM2: 3680,
    rooms: ["bath", "living", "kitchen"],
    description: "Известняк цвета bone. Тёплый светлый камень для современных интерьеров.",
    tags: ["известняк", "камень", "светлый"],
  },
  {
    id: "tile-slate-rust",
    name: "Slate Rust Multicolor",
    brand: "Estima",
    collection: "Hard",
    preview: TILE_IMG.brickRed,
    accent: "#92400e",
    size: [30, 60],
    material: "stone",
    surface: "floor",
    style: "loft",
    altStyles: ["midcentury"],
    pricePerM2: 2580,
    rooms: ["hall", "kitchen", "outdoor"],
    description: "Сланец многоцветный с ржавыми тонами. Морозостойкий.",
    tags: ["сланец", "многоцветный", "улица"],
  },

  // ── КИРПИЧ: ещё цвета ─────────────────────────────────────────
  {
    id: "tile-brick-charcoal",
    name: "Brick Charcoal",
    brand: "Cersanit",
    collection: "Loft",
    preview: TILE_IMG.concreteGrey,
    accent: "#0c0a09",
    size: [6, 25],
    material: "brick",
    surface: "wall",
    style: "loft",
    altStyles: ["modern"],
    pricePerM2: 2080,
    rooms: ["living", "kitchen", "hall"],
    description: "Чёрный кирпич 6×25. Драматичный лофт-акцент.",
    tags: ["кирпич", "чёрный", "драма"],
  },
  {
    id: "tile-brick-cream",
    name: "Brick Cream Aged",
    brand: "Peronda",
    collection: "Manhattan",
    preview: TILE_IMG.subwayWhite,
    accent: "#fef3c7",
    size: [7, 28],
    material: "brick",
    surface: "wall",
    style: "scandi",
    altStyles: ["classic", "midcentury"],
    pricePerM2: 2380,
    rooms: ["living", "kitchen", "hall", "bed"],
    description: "Кремовый состаренный кирпич 7×28. Тёплый европейский лофт.",
    tags: ["кирпич", "кремовый", "состаренный"],
  },

  // ── МОЗАИКА ────────────────────────────────────────────────────
  {
    id: "tile-mosaic-hex-marble",
    name: "Hex Mosaic Marble",
    brand: "Italon",
    collection: "Charme Mosaico",
    preview: TILE_IMG.hexBlack,
    accent: "#fafaf9",
    size: [30, 30],
    material: "mosaic",
    surface: "wall",
    style: "classic",
    altStyles: ["glamour"],
    pricePerM2: 5980,
    rooms: ["bath", "kitchen"],
    description: "Мозаика-шестигранник из мрамора. Декор для душевых ниш.",
    tags: ["мозаика", "шестигранник", "мрамор"],
  },
  {
    id: "tile-mosaic-penny",
    name: "Penny Round Black",
    brand: "Equipe",
    collection: "Penny",
    preview: TILE_IMG.hexBlack,
    accent: "#0a0a0a",
    size: [30, 30],
    material: "mosaic",
    surface: "wall",
    style: "midcentury",
    altStyles: ["modern", "glamour"],
    pricePerM2: 3980,
    rooms: ["bath"],
    description: "Круглая мозаика «пенни» чёрная. Винтажный декор пола ванной.",
    tags: ["мозаика", "пенни", "круглая"],
  },
  {
    id: "tile-mosaic-mother-pearl",
    name: "Mother of Pearl",
    brand: "Vidrepur",
    collection: "Pearl",
    preview: TILE_IMG.subwayWhite,
    accent: "#fde68a",
    size: [30, 30],
    material: "mosaic",
    surface: "wall",
    style: "glamour",
    altStyles: ["classic"],
    pricePerM2: 6980,
    rooms: ["bath"],
    description: "Перламутровая мозаика. Игра света на стене душевой.",
    tags: ["мозаика", "перламутр", "премиум"],
    popular: true,
  },

  // ── БОЛЬШОЙ ФОРМАТ ─────────────────────────────────────────────
  {
    id: "tile-slab-onyx",
    name: "Slab Onyx Backlit",
    brand: "Porcelanosa",
    collection: "XLight",
    preview: TILE_IMG.travertine,
    accent: "#fbbf24",
    size: [120, 240],
    material: "marble",
    surface: "wall",
    style: "glamour",
    altStyles: ["modern"],
    pricePerM2: 12800,
    rooms: ["bath", "living"],
    description: "Слэб под оникс с подсветкой 120×240. Эффект витража.",
    tags: ["слэб", "оникс", "подсветка"],
  },
  {
    id: "tile-slab-wood",
    name: "Slab Wood XL",
    brand: "Italon",
    collection: "Element Wood",
    preview: TILE_IMG.oakPlank,
    accent: "#a16207",
    size: [80, 240],
    material: "wood-look",
    surface: "floor",
    style: "modern",
    altStyles: ["loft", "scandi"],
    pricePerM2: 4980,
    rooms: ["living", "bed", "hall"],
    description: "Под дерево формата 80×240. Минимум швов на полу.",
    tags: ["слэб", "дерево", "большой формат"],
  },

  // ── ТРЕНДЫ 2024-2025 ───────────────────────────────────────────
  {
    id: "tile-zellige-white",
    name: "Zellige White Handmade",
    brand: "Equipe",
    collection: "Artisan",
    preview: TILE_IMG.subwayWhite,
    accent: "#fafaf9",
    size: [10, 10],
    material: "ceramic",
    surface: "wall",
    style: "japandi",
    altStyles: ["scandi", "midcentury"],
    pricePerM2: 4280,
    rooms: ["bath", "kitchen"],
    description: "Zellige 10×10 ручной работы — каждая плитка с уникальной фактурой.",
    tags: ["zellige", "ручная работа", "марокко"],
    popular: true,
  },
  {
    id: "tile-zellige-terracotta",
    name: "Zellige Terracotta",
    brand: "Equipe",
    collection: "Artisan",
    preview: TILE_IMG.brickRed,
    accent: "#9a3412",
    size: [10, 10],
    material: "ceramic",
    surface: "wall",
    style: "midcentury",
    altStyles: ["classic", "japandi"],
    pricePerM2: 4380,
    rooms: ["bath", "kitchen", "living"],
    description: "Zellige терракотовый. Тёплый средиземноморский характер.",
    tags: ["zellige", "терракота", "средиземноморский"],
  },
  {
    id: "tile-rust-oxide",
    name: "Rust Oxide",
    brand: "Atlas Concorde",
    collection: "Mark",
    preview: TILE_IMG.brickRed,
    accent: "#c2410c",
    size: [60, 120],
    material: "porcelain",
    surface: "both",
    style: "loft",
    altStyles: ["modern", "midcentury"],
    pricePerM2: 4180,
    rooms: ["living", "kitchen", "bath"],
    description: "Окисленный металл с эффектом ржавчины. Бруталистский тренд.",
    tags: ["металл", "ржавчина", "бруталист"],
  },

  // ── ЦВЕТНЫЕ АКЦЕНТНЫЕ ──────────────────────────────────────────
  {
    id: "tile-cobalt",
    name: "Cobalt Deep Blue",
    brand: "Equipe",
    collection: "Magical",
    preview: TILE_IMG.emeraldGloss,
    accent: "#1e3a8a",
    size: [12, 12],
    material: "ceramic",
    surface: "wall",
    style: "glamour",
    altStyles: ["classic", "midcentury"],
    pricePerM2: 4480,
    rooms: ["bath", "kitchen"],
    description: "Глубокий кобальт-синий 12×12. Драгоценный акцент в ванной.",
    tags: ["синяя", "кобальт", "акцент"],
  },
  {
    id: "tile-coral-pink",
    name: "Coral Pink Glossy",
    brand: "Vives",
    collection: "World",
    preview: TILE_IMG.emeraldGloss,
    accent: "#fb7185",
    size: [10, 30],
    material: "ceramic",
    surface: "wall",
    style: "glamour",
    altStyles: ["midcentury"],
    pricePerM2: 3780,
    rooms: ["bath", "kitchen", "bed"],
    description: "Коралловый розовый кабанчик. Бьюти-салонный шик.",
    tags: ["метро", "розовая", "коралл"],
  },
  {
    id: "tile-mustard-deco",
    name: "Mustard Deco Square",
    brand: "Peronda",
    collection: "FS Mediterraneo",
    preview: TILE_IMG.moroccan,
    accent: "#ca8a04",
    size: [25, 25],
    material: "ceramic",
    surface: "floor",
    style: "midcentury",
    altStyles: ["classic"],
    pricePerM2: 3580,
    rooms: ["kitchen", "bath", "hall"],
    description: "Горчичный квадрат с этно-узором 25×25. Ретро-кухня.",
    tags: ["узор", "горчичная", "ретро"],
  },
  {
    id: "tile-cream-velvet",
    name: "Cream Velvet Matte",
    brand: "Cersanit",
    collection: "Velvet",
    preview: TILE_IMG.travertine,
    accent: "#fef3c7",
    size: [60, 60],
    material: "ceramic",
    surface: "both",
    style: "japandi",
    altStyles: ["scandi", "modern"],
    pricePerM2: 1980,
    rooms: ["living", "bed", "bath"],
    description: "Кремовая бархатная плитка 60×60. Бюджетная база для тёплых интерьеров.",
    tags: ["бежевая", "бархат", "бюджет"],
  },
];

/* ─────────────────── HELPERS ─────────────────── */

export const TILE_MATERIAL_LABELS: Record<TileMaterial, string> = {
  porcelain:  "Керамогранит",
  ceramic:    "Керамика",
  marble:     "Мрамор",
  stone:      "Камень",
  "wood-look": "Под дерево",
  concrete:   "Бетон",
  mosaic:     "Мозаика",
  brick:      "Кирпич",
};

export const TILE_SURFACE_LABELS: Record<TileSurface, string> = {
  floor: "Пол",
  wall:  "Стены",
  both:  "Универсальная",
};

export const TILE_ROOM_LABELS: Record<TileItem["rooms"][number], string> = {
  kitchen: "Кухня",
  bath:    "Ванная",
  living:  "Гостиная",
  bed:     "Спальня",
  hall:    "Прихожая",
  outdoor: "Улица",
};

export function searchTiles(items: TileItem[], query: string): TileItem[] {
  const q = query.trim().toLowerCase();
  if (!q) return items;
  return items.filter((it) => {
    const hay = [
      it.name,
      it.brand,
      it.collection ?? "",
      it.description,
      ...it.tags,
    ].join(" ").toLowerCase();
    return hay.includes(q);
  });
}

export function filterTilesByStyle(items: TileItem[], style: TileStyle | "all"): TileItem[] {
  if (style === "all") return items;
  return items.filter((it) => it.style === style || (it.altStyles ?? []).includes(style));
}

export function filterTilesBySurface(items: TileItem[], surface: TileSurface | "all"): TileItem[] {
  if (surface === "all") return items;
  return items.filter((it) => it.surface === surface || it.surface === "both");
}

export function filterTilesByRoom(items: TileItem[], room: TileItem["rooms"][number] | "all"): TileItem[] {
  if (room === "all") return items;
  return items.filter((it) => it.rooms.includes(room));
}

export function formatTilePrice(n: number): string {
  return new Intl.NumberFormat("ru-RU").format(n) + " ₽/м²";
}